site_name: 程序员常用工具使用教程
theme: material
repo_url: https://github.com/fuuqiu/mdTools
copyright:  Email:Fuuqiu@gmail.com </br> 支持提供优化方案
site_description: Fuuqiu编写的开发常用工具快速使用笔记
site_author: Fuuqiu@gmail.com
